slicer_exe_path: C:\\Path\\To\\Slicer.exe
photo_data_dir: C:\\Path\\To\\Photograph\\Data\\Directory
batch:
	mri_data_dir: C:\\Path\\To\\FreeSurfer\\Subjects
	subject_dir_regex: RESP*
	reprocess: false
	process_only_photo: false
	process_only_envelope: false
  process_only_envelope: false